#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
IFS='/' read -r FIRST_PART _ <<< "$BRANCH_NAME"
KEYWORDS=("release" "hotfix")

for keyword in "${KEYWORDS[@]}"; do
    if [ "$FIRST_PART" == "$keyword" ]; then
        if [ "$SKIP_SIMPLE_GIT_HOOKS" = "1" ]; then
            echo "[INFO] SKIP_SIMPLE_GIT_HOOKS is set to 1, skipping hook."
            exit 0
        fi

        if [ -f "$SIMPLE_GIT_HOOKS_RC" ]; then
            . "$SIMPLE_GIT_HOOKS_RC"
        fi

        npm run changelog --filter=tech-fix

        git add CHANGELOG.md
        git commit -m "Добавлен список изменений в changelog"
        
        exit 0
    fi
done